### PR TITLE
Fix revenue account computation

### LINKED ISSUE #425: Distriubtion condition must match regexp for validation
## Expected Behavior
Condition in: https://github.com/iov-one/weave/blob/master/x/distribution/model.go#L120  must match https://github.com/iov-one/weave/blob/master/conditions.go#L23

## Actual Behavior
It fails as the prefix `distribution` is >8 chars as defined in the regexp

### PR DESCRIPTION
**Pull request by husio**
When computing the revenue account address, validate created condition
first.

fix #425

### CODE REVIEW

File: x/distribution/model.go [hunk 1]
```diff
@@ -116,8 +116,12 @@ func (b *RevenueBucket) Create(db weave.KVStore, rev *Revenue) (orm.Object, erro
 
 // RevenueAccount returns an account address that is holding funds of a revenue
 // with given ID.
-func RevenueAccount(revenueID []byte) weave.Address {
-	return weave.NewCondition("distribution", "revenue", revenueID).Address()
+func RevenueAccount(revenueID []byte) (weave.Address, error) {
```
Comment (alpe) [inline x/distribution/model.go]: It is 👍 to check and return an error. We usually do it a bit different with [escrow](https://github.com/iov-one/weave/blob/master/x/escrow/model.go#L90) or [multisig](https://github.com/iov-one/weave/blob/master/x/multisig/context.go#L29) for example where we return the condition rather than the address and let the caller decide on calling validate.
