### PR TITLE
x/aswap: allow timeout to be any value after 1970-01-01

### LINKED ISSUE #718: Remove timeout restriction for atomic swap
## Expected Behavior

A user can choose an arbitrary timeout

## Actual Behavior

With the migration from escrow to aswap, a new minimal timeout of 24 hours from now was introduced

## Steps to Reproduce the Problem

weave v0.15.0, aswap module

## Additional info

Surprisingly, the blockchain got oppinionated about the question which atomic swap timeout is good for the user. On the one hand there are multiple risks related to timeouts that are not choosen wisely, many of which are discussed in https://github.com/iov-one/iov-core/blob/master/docs/atomic-swap-protocol-v1.md#risks. On the other hand, the minimal timeout makes high frequent trades impossible (which might very well be super low value trades).

Since the blockchain can never be clever enough to make a judgement, which timeout is good for which user in which situation, we should not pretend we are able to take that responsibility from the user. Timeout handling must be done in the client and needs to be carefully crafted in terms of UX, to allow the user to make smart decisions in a guided fashion. Thus I think we should remove any restriction on the timeout.

From a correctness perspective, there is also nothing wrong with timouts set in the past.

### PR DESCRIPTION
**Pull request by husio**
Do not limit swap timeout to be only a certain value in the future.

resolve #718

### CODE REVIEW

File: x/aswap/handler.go [hunk 1]
```diff
@@ -102,10 +102,6 @@ func (h CreateSwapHandler) validate(ctx weave.Context,
 	if err := weave.LoadMsg(tx, &msg); err != nil {
 		return nil, errors.Wrap(err, "load msg")
 	}
-	if weave.IsExpired(ctx, msg.Timeout.Add(-MinTimeout)) {
```
Comment (webmaster128) [inline x/aswap/handler.go]: Can `MinTimeout` be deleted now?
