### PR TITLE
fix sequence key creation

### LINKED ISSUE #168: duplicated sequence prefix
`Sequence` is generating keys with duplicated prefix.

When [creating a new sequence](https://github.com/iov-one/weave/blob/3b7376feba386a20c4c4e9411dee4fdfa2becc7f/orm/sequence.go#L24), sequence ID is prefixed with `seqPrefix`. When building a key for [reading a sequence state](https://github.com/iov-one/weave/blob/3b7376feba386a20c4c4e9411dee4fdfa2becc7f/orm/sequence.go#L41), sequence ID is additionally prefixed with `seqPrefix`.

Expected sequence state key is in format ` _s.<bucket>:<name>`. Current implementation is using `
 _s._s.<bucket>:<name>`

### PR DESCRIPTION
**Pull request by husio**
Remove sequence duplicate prefix. Refactor and cleanup sequence code.

fix #168

This pull request came up much bigger than expected. :rabbit: :hole:

### CODE REVIEW

File: orm/sequence.go [hunk 1]
```diff
@@ -6,50 +6,42 @@ import (
...
-}
-
-func (s *Sequence) increment(db weave.KVStore) (int64, []byte) {
-	key, bz := s.curVal(db)
-	val := decodeSequence(bz)
-	val++
-	bz = encodeSequence(val)
-	db.Set(key, bz)
-	return val, bz
+func (s *Sequence) increment(db weave.KVStore, inc int64) (int64, []byte) {
```
Comment (ruseinov) [inline orm/sequence.go]: I'm not sure what is the point of having inc parameter there?
If it's not used with values other than 1 - I'd remove this. Increment
without a value is known to increment by 1, so that does not need to be explicit

Comment (ruseinov) [reply orm/sequence.go]: Ok, I see now why you did this.
Disregard

File: orm/sequence_test.go [hunk 2]
```diff
@@ -1,52 +1,41 @@
...
+		NewSequence("bucket-name-2", "sequence-name-1"),
+		NewSequence("bucket-name-2", "sequence-name-2"),
 	}
-
-	for i, tc := range cases {
-		t.Run(fmt.Sprintf("case-%d", i), func(t *testing.T) {
-			s := NewSequence(tc.bucket, tc.name)
-			_, orig := s.curVal(db)
-
-			val := incrementN(s, db, tc.increments)
```
Comment (ruseinov) [inline orm/sequence_test.go]: I think it might still be cool to test increment method with various arguments.

Comment (husio) [reply orm/sequence_test.go]: `incrementN` no longer exists.

`Sequence.increment` is not tested explicitly. You can trust that it works, because it is [used in tests to set up environment](https://github.com/iov-one/weave/blob/61039d6c9c8b8215a6e2127cba72f45ca0971658/orm/bucket_test.go#L152). If it was not increment the sequence correctly, the test would not succeed. Do you think this is enough, or it still requires explicit test?

Comment (ruseinov) [reply orm/sequence_test.go]: @husio we have 100% coverage there, so I guess this is fine
