### PR TITLE
x/username: fix memory leak on username import

### LINKED ISSUE #900: Figure out why weave uses too much memory when trying to import many names (25k names on kissnet)
Currently when we are using a huge genesis like this even 4gb of memory is not enough.

Gotta investigate this to see what is the root cause of this issue.

### PR DESCRIPTION
**Pull request by ruseinov**
Fixes #900

### CODE REVIEW

**Comment by iov-bot-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry. <br />
You can find it at <a href="https://github.com/iov-one/weave/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

File: handler.go [hunk 1]
```diff
@@ -60,6 +63,49 @@ func (o Options) ReadOptions(key string, obj interface{}) error {
...
+	if _, err := dec.Token(); err != nil {
+		return nil, errors.Wrapf(errors.ErrInput, "opening bracket %s", err)
+
+	}
+
+	closed := false
+
+	return func(obj interface{}) error {
+		if closed {
+			return errors.Wrap(errors.ErrState, "closed")
```
Comment (husio) [inline handler.go]: This could return the same error type as no more data does (`ErrEmpty` or `ErrIterationDone`). For the user it will be easier to handle, because it does not require a separate handling. And the API is simplified -- calling a done iterator function is safe and always returns the same result.

File: handler.go [hunk 2]
```diff
@@ -60,6 +63,49 @@ func (o Options) ReadOptions(key string, obj interface{}) error {
 	return json.Unmarshal(msg, obj)
 }
 
+// Stream expects an array of json elements and allows to process them sequentially
+// this helps when one needs to parse a large json without having any memory leaks.
+// Returns ErrEmpty on empty key or when there are no more elements.
+// Returns ErrState when the stream has finished/encountered a Decode error.
+func (o Options) Stream(key string) (func(obj interface{}) error, error) {
```
Comment (husio) [inline handler.go]: I think the `Stream` interface could be improved to return only an iterator function.

```go
 func (o Options) Stream(key string) (loadNext func(dest interface{}) error) {
```
`Stream` function must first complete preparation steps before it can return an iterator. It can do this and instead of instantly returning an error, provide a callback that will return it. The benefit is that for the user of this API, this function always returns an iterator and you have one less error case to check:
```go
func (o Options) Stream(key string) (loadNext func(dest interface{}) error) {  
        if _, ok := o[key]; !ok {                                              
                return func(interface{}) error {                               
                        errors.Wrap(err, "foo")                                
                }                                                              
        }                                                                      
                                                                               
        if _, err := dec.Token(); err != nil {                                 
                return func(interface{}) error {                               
                        errors.Wrap(err, "bar")                                
                }                                                              
        }                                                                      
                                                                               
        // ...                                                                 
                                                                               
        return func(dest interface{}) error {                                  
                // ...                                                         
        }                                                                      
}            
```

File: handler.go (hunk 1 above)
Comment (ruseinov) [reply handler.go]: I was thinking about it, the closed bit only happens when we returned an error already so it does not in fact require any handling unless the client does something wrong.
That is why I'd like to keep it as different error and be able to differentiate. `ErrState` shouldn't ever be reached by any client that does it's error handling right.

File: handler.go [hunk 3]
```diff
@@ -60,6 +63,49 @@ func (o Options) ReadOptions(key string, obj interface{}) error {
...
+	msg := o[key]
+	if len(msg) == 0 {
+		return nil, errors.Wrap(errors.ErrEmpty, "data")
```
[the remark this answers is not in the document]
Comment (ruseinov) [reply handler.go]: I think keeping this consistent to the `ReadOptions` function is better, as for us here `ErrEmpty` is basically the same as noop for `ReadOptions`.

As `Stream` is basically a performance improvement for `ReadOptions` I think it's fair. In which case `ErrEmpty` is a better fit, because it wouldn't require separate handling for when key is not found/iterator has finished. As the only usage example of this we have does not care about the presence of the key and it seems like none of the ones that use `ReadOptions` do too - I'd like to keep it that way.

File: handler.go (hunk 2 above)
Comment (ruseinov) [reply handler.go]: Yeah, I can return the error within the function, that's fair.

**Comment by ruseinov** [comment]
@husio I have cleaned up the api to return errors only from the iterator. 
As to the other comments - I've explained my reasoning better and hope that now
it's a bit easier to understand the decisions that have been made.
