### PR TITLE
Tx result call stack dislay controlled by flag

### LINKED ISSUE #97: Add flag to bcpd to show/hide stack trace on abci errors
Ethan thinks there is a todo there in top level result.go. Let's do it

### PR DESCRIPTION
**Pull request by lehajam**
Fix #97 

- [x] Add bool param to control CheckTxError and DeliverTxError verbosity
- [x] Add flag to bcpd to control CheckTxError and DeliverTxError verbosity

### CODE REVIEW

File: abci.go [hunk 1]
```diff
@@ -14,19 +14,19 @@ import (
 // DeliverOrError returns an abci response for DeliverTx,
 // converting the error message if present, or using the successful
 // DeliverResult
-func DeliverOrError(result DeliverResult, err error) abci.ResponseDeliverTx {
+func DeliverOrError(result DeliverResult, err error, debug bool) abci.ResponseDeliverTx {
```
Comment (ethanfrey) [inline abci.go]: Hmm... I had thought of a state variable in this module, but if you can pass it in as an arg, that is cleaner.

File: abci_test.go [hunk 2]
```diff
@@ -36,7 +36,7 @@ func TestCreateErrorResult(t *testing.T) {
 			assert.Contains(t, dres.Log, "iov-one/weave/abci")
 			assert.Equal(t, tc.code, dres.Code)
 
-			cres := weave.CheckTxError(tc.err)
+			cres := weave.CheckTxError(tc.err, true)
```
Comment (ethanfrey) [inline abci_test.go]: Good to extend this for the true and false case, that they both start with the same string (expected from the error), and the stack trace is only present with debug=true

File: app/base.go [hunk 3]
```diff
@@ -14,27 +14,29 @@ type BaseApp struct {
 	decoder weave.TxDecoder
 	handler weave.Handler
 	ticker  weave.Ticker
+	debug   bool
```
Comment (ethanfrey) [inline app/base.go]: Yeah, I guess this is the most appropriate place to store the debug state. Good call.

File: commands/server/start.go [hunk 4]
```diff
@@ -13,31 +13,34 @@ import (
...
+	startFlags.BoolVar(&debug, flagDebug, false, "call stack returned with Tx result")
 	err := startFlags.Parse(args)
-	return addr, err
+	return addr, debug, err
 }
 
 // AppGenerator lets us lazily initialize app, using home dir
 // and logger potentially initialized with other flags
-type AppGenerator func(string, log.Logger) (abci.Application, error)
+type AppGenerator func(string, log.Logger, bool) (abci.Application, error)
```
Comment (ethanfrey) [inline commands/server/start.go]: Yes, you did update the definition of what it expects to match. Nice.

File: commands/server/start.go [hunk 5]
```diff
@@ -13,31 +13,34 @@ import (
...
 )
 
-func parseBind(args []string) (string, error) {
+func parseFlags(args []string) (string, bool, error) {
 	// parse flagBind and return the result
 	var addr string
+	var debug bool
 	startFlags := flag.NewFlagSet("start", flag.ExitOnError)
 	startFlags.StringVar(&addr, flagBind, "tcp://localhost:46658", "address server listens on")
+	startFlags.BoolVar(&debug, flagDebug, false, "call stack returned with Tx result")
```
Comment (ethanfrey) [inline commands/server/start.go]: maybe `call stack returned on Tx error` (definitely not on result, which implies success)
