### PR TITLE
initial batch

### LINKED ISSUE #102: Add batch transaction
It would be great to have a message (BatchMessage) that encapsulates a list of messages. They will all get executed in order and all abort if any fail.

Simple usage is one tx for swap on one chain. The BatchMessage contains eg. SendMsg (A->B 10 ETH) and SendMsg (B -> A 50 IOV). This tx must be signed by A and B. If either have a bad nonce, bad sig, or too low balance, then both fail.

You can quickly imagine other scenarios, like transfering ownership of an NFT against a payment, etc.

Seems like a simple and powerful building block for client libraries to add security.

### PR DESCRIPTION
**Pull request by ruseinov**
Closes #102 
This is an initial version of batch tx.
My only concern here is I create my own batch tx type to be able to pass transactions with messages down the line.

If that looks good - I'll add tests and plug that in.

### CODE REVIEW

**Comment by ruseinov** [comment]
@ethanfrey this has been sitting in my git stash for a while as we're busy with other pressing things, so I figured it needs a little push as it provides us with some crucial functionality for bnsd

File: x/batch/decorator.go [hunk 1]
```diff
@@ -0,0 +1,136 @@
...
+// Check iterates through messages in a batch transaction and passes them
+// down the stack
+func (d Decorator) Check(ctx weave.Context, store weave.KVStore, tx weave.Tx,
+	next weave.Checker) (res weave.CheckResult, err error) {
+	msg, err := tx.GetMsg()
+	if err != nil {
+		return
+	}
+
+	if batchMsg, ok := msg.(*ExecuteBatchMsg); ok {
```
Comment (alpe) [inline x/batch/decorator.go]: pp: if `!ok -> next` to have the main flow aligned on the left.

File: x/batch/decorator.go [hunk 2]
```diff
@@ -0,0 +1,136 @@
...
+// Deliver iterates through messages in a batch transaction and passes them
+// down the stack
+func (d Decorator) Deliver(ctx weave.Context, store weave.KVStore, tx weave.Tx,
+	next weave.Deliverer) (res weave.DeliverResult, err error) {
+	msg, err := tx.GetMsg()
+	if err != nil {
+		return
+	}
+
+	if batchMsg, ok := msg.(*ExecuteBatchMsg); ok {
```
Comment (alpe) [inline x/batch/decorator.go]: pp: same as above

File: x/batch/decorator.go [hunk 3]
```diff
@@ -0,0 +1,136 @@
...
+	logs := make([]string, len(delivers))
+	var payments int64
+	var diffs []types.ValidatorUpdate
+	var tags []common.KVPair
+	for i, r := range delivers {
+		datas[i] = r.Data
+		logs[i] = r.Log
+		payments += r.GasUsed
+		if len(r.Diff) > 0 {
+			diffs = append(diffs, r.Diff...)
```
Comment (alpe) [inline x/batch/decorator.go]: q: would adding, removing the same validator work with tendermint?

File: x/batch/decorator.go [hunk 4]
```diff
@@ -0,0 +1,136 @@
...
+		}
+		if len(r.Tags) > 0 {
+			tags = append(tags, r.Tags...)
```
Comment (alpe) [inline x/batch/decorator.go]: q: what happens when we add `foo:bar` and `foo:other` ? I remember some discussion with @ethanfrey that this is not going to work with tendermint. We can can test and fail the batch delivery if it is not supported,IMHO.

File: x/batch/decorator.go [hunk 5]
```diff
@@ -0,0 +1,136 @@
...
+		}
+	}
+	return weave.DeliverResult{
+		Data:    amino.MustMarshalBinary(datas),
+		Log:     strings.Join(logs, "\n"),
```
Comment (alpe) [inline x/batch/decorator.go]: q: same questions about data and log as with CheckResult

File: x/batch/msg.go [hunk 6]
```diff
@@ -0,0 +1,25 @@
...
+)
+
+var _ weave.Msg = (*ExecuteBatchMsg)(nil)
+
+func (*ExecuteBatchMsg) Path() string {
+	return PathExecuteBatchMsg
+}
+
+func (m *ExecuteBatchMsg) Validate() error {
+	for _, v := range m.Messages {
```
Comment (alpe) [inline x/batch/msg.go]: req: Please limit the number of messages allowed in a batch. Also batches must not include other batches but that is probably defined in protobuf.

File: x/batch/codec.proto [hunk 7]
```diff
@@ -0,0 +1,48 @@
...
+import "github.com/iov-one/weave/x/nft/username/codec.proto";
+import "github.com/iov-one/weave/x/nft/bootstrap_node/codec.proto";
+import "github.com/iov-one/weave/x/validators/codec.proto";
+
+// ExecuteBatchMsg encapsulates multiple messages to support batch transaction
+message ExecuteBatchMsg {
+    repeated Msg messages = 1 [(gogoproto.nullable) = false];
+    // Msg is a workaround as protobuf does not support repeated oneof
+    message Msg {
+        oneof msg {
```
[the remark this answers is not in the document]
Comment (ruseinov) [reply x/batch/codec.proto]: @alpe Since this is an extension I'm afraid we will have to deal with all the messages weave supports.
We are dealing with limitations of protobuf here mostly. 

It's super easy to fix this if we could forgo the protobuf codec for this particular case, but I'm afraid we have to be repetitive and verbose, look at how bnsd and bcpd codecs look for "inspiration".

File: x/batch/decorator.go [hunk 8]
```diff
@@ -0,0 +1,136 @@
...
+	logs := make([]string, len(checks))
+	var allocated, payments int64
+	for i, r := range checks {
+		datas[i] = r.Data
+		logs[i] = r.Log
+		allocated += r.GasAllocated
+		payments += r.GasPayment
+	}
+	return weave.CheckResult{
+		Data:         amino.MustMarshalBinary(datas),
```
[the remark this answers is not in the document]
Comment (ruseinov) [reply x/batch/decorator.go]: @alpe It has nothing to do with protobuf.
This implementation is inspired by @ethanfrey implementation from older cosmos sdk which used go-wire, which is now go-amino.

go-amino is going to be used anyway as we are dealing with tendermint, so this is a valid approach in my understanding.

File: x/batch/decorator.go [hunk 9]
```diff
@@ -0,0 +1,136 @@
...
+		Log:          strings.Join(logs, "\n"),
```
[the remark this answers is not in the document]
Comment (ruseinov) [reply x/batch/decorator.go]: This also has been inspired by earlier implementations, I think newline is good enough and also individual messages are not very helpful in this case, it is easy to break down by new line as needed though

File: x/batch/codec.proto (hunk 7 above)
[the remark this answers is not in the document]
Comment (ethanfrey) [reply x/batch/codec.proto]: I think we will need to repeat somehow, but alex is right, this is application specific and should be in the `cmd/*/app` dir, not in batch. If in batch, then batch is tied to exactly one app and not re-usable.

File: x/batch/decorator.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (ethanfrey) [reply x/batch/decorator.go]: Oh, please don't use go-amino. 🙏 
There is absolutely *zero* support for it in any language outside of golang. Even with months of requests and assurances from the tendermint team that it is easy to port.

I showed the version I wrote before to give some inspiration, but please don't use this codec..

[the remark this answers is not in the document]
Comment (ethanfrey) [reply x/batch/decorator.go]: BTW, tendermint doesn't use go-amino outside of the p2p interface.

The main use is in cosmos-sdk. And go-amino is exactly the reason we have no adaptor client side that works with them

File: x/batch/decorator.go (hunk 4 above)
Comment (ethanfrey) [reply x/batch/decorator.go]: This is a bit of a bug tendermint side.

There is no fail, and the tags are all stored. You can also search for them.
However, a subscription will only receive one of the tags with the same key.

We work around this in weave by placing what would be `key=value` into `key:value=1`, so they should always be unique unless it really is the same tag.

File: x/batch/decorator.go (hunk 5 above)
Comment (ethanfrey) [reply x/batch/decorator.go]: remove this `amino.MustMarshalBinary(datas)`.

Also most formats is fine, as long as the client can parse it out and map the results back to the original messages in the transaction. You can use something like this to hold the data: https://github.com/iov-one/weave/blob/master/app/results.proto

You could also use a similar structure for the logs, which is more correct than assuming no `"\n"` in the individual log messages. The existing join is "ok", but I would kind of prefer the protobuf approach

File: x/batch/msg.go (hunk 6 above)
Comment (ethanfrey) [reply x/batch/msg.go]: Maybe 10? But yeah, any constant is good to enforce and easily adjust later

**Comment by ruseinov** [comment]
@ethanfrey @alpe thanks for clarifications, will do these changes today

**Comment by ruseinov** [comment]
@ethanfrey was not sure about amino so figured I would clone your wire approach and see what options we have

File: x/batch/codec.proto (hunk 7 above)
[the remark this answers is not in the document]
Comment (ruseinov) [reply x/batch/codec.proto]: @ethanfrey makes sense, I always forget about the fact that one could extend weave outside it's codebase and add messages.
I will code that to some BatchMsg interface to allow defining these within the app.

File: x/batch/decorator.go (hunk 5 above)
Comment (ruseinov) [reply x/batch/decorator.go]: @ethanfrey got it, let's default to protobuf approach everywhere to be consistent. Also, protobuf kind of solves the issue with parsing things for us.

@alpe you were right, I just didn't fully understand what you were meaning by that.

File: x/batch/msg.go (hunk 6 above)
Comment (ruseinov) [reply x/batch/msg.go]: @ethanfrey 10 it is, going to be a constant so we can change it.
I keep wondering if it might be cool to include this config variable in genesis and default to something when it does not exist?

Comment (ethanfrey) [reply x/batch/msg.go]: > I keep wondering if it might be cool to include this config variable in genesis and default to something when it does not exist?

Yes, nice idea. We can do this a few other places, to read constants from the genesis file. Issue is, we only get the genesis file on `init`, so for restart, this needs to be persisted to the kvstore.

Please make some reusable code for this, and happy to use this other places. I started doing this ages ago for fees, but never finished the PR as I had 1000 other things and it wasn't priority. Maybe this code gives some ideas, but it is not polished or tested fully, so don't copy, just compare those ideas to yours.
https://github.com/iov-one/weave/pull/41

**Comment by ruseinov** [comment]
@alpe ci is showing something weird, as there is no such message anymore. gotta investigate, maybe just a travis glitch

File: cmd/bcpd/app/codec.proto [hunk 10]
```diff
@@ -13,7 +14,20 @@ import "github.com/iov-one/weave/x/validators/codec.proto";
...
+  // signatures, autogenerates GetSignatures()
+  repeated sigs.StdSignature signatures = 3;
+  // preimage for hashlock, autogenerates GetPreimage
+  bytes preimage = 4;
+  // id of multisig contract, autogenerates GetMultisig
+  repeated bytes multisig = 5;
+}
+
+
+message Sum {
```
Comment (webmaster128) [inline cmd/bcpd/app/codec.proto]: Is `Sum` a union type (`Sum` queals `cash.SendMsg` or `namecoin.NewTokenMsg` or ... or `BatchMsg`)? Then I think `Union` would be the better name

File: cmd/bcpd/app/codec.proto [hunk 11]
```diff
@@ -27,13 +41,11 @@ message Tx {
     multisig.UpdateContractMsg update_contract_msg = 9;
     // validators actions
     validators.SetValidatorsMsg set_validators_msg = 10;
+    BatchMsg batch_msg = 11;
```
Comment (webmaster128) [inline cmd/bcpd/app/codec.proto]: Is this supposed to be recursive? A BatchMsg contains multiple BatchMsg that contain multiple BatchMsg …?

File: cmd/bcpd/app/codec.proto [hunk 12]
```diff
@@ -13,7 +14,20 @@ import "github.com/iov-one/weave/x/validators/codec.proto";
 // Tx contains the message
 message Tx {
   // msg is a sum type over all allowed messages on this chain.
-  oneof sum{
+  Sum sum = 1;
```
Comment (webmaster128) [inline cmd/bcpd/app/codec.proto]: Is `sum` a good name for this field? Why not `message` anaolue to `BatchMsg`?

File: cmd/bcpd/app/codec.proto (hunk 11 above)
Comment (ruseinov) [reply cmd/bcpd/app/codec.proto]: I think you are right, we need to implement a manual validation there, so I guess it's best if we separate tx and batchMsg sum stuff

File: cmd/bcpd/app/codec.proto (hunk 12 above)
Comment (ruseinov) [reply cmd/bcpd/app/codec.proto]: It's not, it's just what we had before

File: cmd/bcpd/app/codec.proto (hunk 10 above)
Comment (ruseinov) [reply cmd/bcpd/app/codec.proto]: It is

**Comment by ruseinov** [comment]
@webmaster128 nice catch, I didn't think about batch in terms of being included in sum.
The idea was to have the same list of messages for both tx and batch, but I can see now that this won't work. I will revert these changes and duplicate

File: x/batch/decorator.go [hunk 13]
```diff
@@ -0,0 +1,164 @@
...
+	var res weave.DeliverResult
+	var err error
+
+	msg, err := tx.GetMsg()
+	if err != nil {
+		return res, err
+	}
+
+	if batchMsg, ok := msg.(Msg); ok {
+		msgList := batchMsg.MsgList()
```
Comment (ethanfrey) [inline x/batch/decorator.go]: No check of max length here?
 I would pull something like:

```
	msg, err := tx.GetMsg()
	if err != nil {
		return res, err
	}
 	if batchMsg, ok := msg.(Msg); ok {
		msgList := batchMsg.MsgList()
		if len(msgList) > maxBatcMessages {
			//TODO: Figure out if this is the correct error
			return res, errors.ErrTooLarge()
		}
```

into a `validate()` method that extracts the message list (or nil or error), then we have the same checks on Check and Deliver.

File: x/batch/decorator.go [hunk 14]
```diff
@@ -0,0 +1,164 @@
...
+	return next.Check(ctx, store, tx)
+}
+
+// combines all data bytes as a go-amino array.
+// joins all log messages with \n
+func (*Decorator) combineChecks(checks []weave.CheckResult) weave.CheckResult {
+	datas := make([][]byte, len(checks))
+	logs := make([][]byte, len(checks))
+	var allocated, payments int64
+	for i, r := range checks {
```
Comment (ethanfrey) [inline x/batch/decorator.go]: This seems a bit clunky coming from looking at some functional code, but is correct and probably the best we can do in golang.

File: x/batch/decorator.go (hunk 3 above)
Comment (ethanfrey) [reply x/batch/decorator.go]: I think we join between multiple tx before sending them to tendermint, and if the same validator id appears multiple times, we just use the last value. This reduction will work with the same validator appearing once in two distinct transactions, or twice in one transaction.

https://github.com/iov-one/weave/blob/master/app/store.go#L335-L347

File: cmd/bcpd/app/codec.proto [hunk 15]
```diff
@@ -27,13 +28,38 @@ message Tx {
     multisig.UpdateContractMsg update_contract_msg = 9;
     // validators actions
     validators.SetValidatorsMsg set_validators_msg = 10;
+    BatchMsg batch_msg = 11;
   }
   // fee info, autogenerates GetFees()
-  cash.FeeInfo fees = 20;
+  cash.FeeInfo fees = 12;
```
[the remark this answers is not in the document]
Comment (ruseinov) [reply cmd/bcpd/app/codec.proto]: @ethanfrey unfortunately at this point we might need to break things, I will check what's possible and maybe introduce this breaking change as part of this PR. Need to revisit all the numbers and see if they could still fit.

File: cmd/bnsd/app/examples.go [hunk 16]
```diff
@@ -67,41 +61,6 @@ func Examples() []commands.Example {
 	}
 	tx.Signatures = []*sigs.StdSignature{sig}
 
-	guest := crypto.GenPrivKeyEd25519().PublicKey().Address()
```
[the remark this answers is not in the document]
Comment (ruseinov) [reply cmd/bnsd/app/examples.go]: @ethanfrey this is an artifact of my revert, going to get this back

File: cmd/bcpd/app/codec.proto (hunk 15 above)
[the remark this answers is not in the document]
Comment (ruseinov) [reply cmd/bcpd/app/codec.proto]: @ethanfrey All good, got this fixed.

File: x/batch/msg.go (hunk 6 above)
Comment (ruseinov) [reply x/batch/msg.go]: @ethanfrey I've been wondering: why don't we use initializer for that as well?
And then query the kv store for values we need.

This has it's drawbacks though, but if we need to store this in KV, why bother?

Comment (ruseinov) [reply x/batch/msg.go]: I need to think about this a bit more though

File: cmd/bcpd/app/app.go [hunk 17]
```diff
@@ -44,6 +45,8 @@ func Chain(minFee x.Coin, authFn x.Authenticator) app.Decorators {
 		namecoin.NewFeeDecorator(authFn, minFee),
 		// cannot pay for fee with hashlock...
 		hashlock.NewDecorator(),
+		// make sure we execute all the transactions in batch before the save point
+		batch.NewDecorator(),
```
Comment (alpe) [inline cmd/bcpd/app/app.go]: req: the batch decorator should be ordered first after `utils.NewSavepoint().OnCheck()` to apply the other decorators at each message of the batch. Otherwise the context could not be set for them.

File: cmd/bcpd/app/msg.go [hunk 18]
```diff
@@ -0,0 +1,56 @@
...
+			case *BatchMsg_Union_UpdateEscrowMsg:
+				return t.UpdateEscrowMsg, nil
+			case *BatchMsg_Union_CreateContractMsg:
+				return t.CreateContractMsg, nil
+			case *BatchMsg_Union_UpdateContractMsg:
+				return t.UpdateContractMsg, nil
+			case *BatchMsg_Union_SetValidatorsMsg:
+				return t.SetValidatorsMsg, nil
+			default:
+				return nil, errors.ErrUnknownTxType(t)
```
Comment (alpe) [inline cmd/bcpd/app/msg.go]: pp: I am afraid we will easily forget about this function when adding new message types to protobuf. Reflection may be helpful indeed. Otherwise only high level tests would cover this. But we are in the same situation with TX type already.

File: cmd/bnsd/app/app.go [hunk 19]
```diff
@@ -50,6 +51,8 @@ func Chain(minFee x.Coin, authFn x.Authenticator) app.Decorators {
 		namecoin.NewFeeDecorator(authFn, minFee),
 		// cannot pay for fee with hashlock...
 		hashlock.NewDecorator(),
+		// make sure we execute all the transactions in batch before the save point
+		batch.NewDecorator(),
```
Comment (alpe) [inline cmd/bnsd/app/app.go]: req: same as in bcpd: please put higher in the chain

File: x/batch/decorator.go [hunk 20]
```diff
@@ -0,0 +1,167 @@
...
+
+var _ weave.Decorator = Decorator{}
+
+// NewDecorator returns a batch transaction decorator
+func NewDecorator() Decorator {
+	return Decorator{}
+}
+
+type BatchTx struct {
+	weave.Tx
```
Comment (alpe) [inline x/batch/decorator.go]: q: why do you need to store `weave.Tx`? It would be more straight forward for me to impl the Marshall/ Unmarshal here with Msg.Marshall/Unmarshal or just raising an error rather than returning something unrelated.

File: x/batch/decorator.go [hunk 21]
```diff
@@ -0,0 +1,167 @@
...
+	Msg weave.Msg
```
Comment (alpe) [inline x/batch/decorator.go]: pp: can be lower case

File: x/batch/decorator.go [hunk 22]
```diff
@@ -0,0 +1,167 @@
...
+func (d Decorator) Check(ctx weave.Context, store weave.KVStore, tx weave.Tx,
+	next weave.Checker) (weave.CheckResult, error) {
+	var res weave.CheckResult
+	var err error
+	msg, err := tx.GetMsg()
+	if err != nil {
+		return res, err
+	}
+
+	if batchMsg, ok := msg.(Msg); ok {
```
Comment (alpe) [inline x/batch/decorator.go]: pp: if you would invert the condition, you can have the happy path aligned to the left.

File: x/batch/decorator.go [hunk 23]
```diff
@@ -0,0 +1,167 @@
...
+	next weave.Deliverer) (weave.DeliverResult, error) {
+	var res weave.DeliverResult
+	var err error
+
+	msg, err := tx.GetMsg()
+	if err != nil {
+		return res, err
+	}
+
+	if batchMsg, ok := msg.(Msg); ok {
```
Comment (alpe) [inline x/batch/decorator.go]: pp: if you would invert the condition, you can have the happy path aligned to the left.

File: x/batch/msg.go [hunk 24]
```diff
@@ -0,0 +1,30 @@
...
+
+func Validate(msg Msg) error {
+	l, err := msg.MsgList()
+	if err != nil {
+		return errors.Wrap(err)
+	}
+
+	if len(l) > MaxBatchMessages {
+		//TODO: Figure out if this is the correct error
+		return errors.ErrTooLarge()
```
Comment (alpe) [inline x/batch/msg.go]: pp: let's have a custom error type that is more descriptive, like too many elements

File: x/batch/msg.go [hunk 25]
```diff
@@ -0,0 +1,30 @@
...
+type Msg interface {
+	weave.Msg
+	x.Validater
+	MsgList() ([]weave.Msg, error)
+}
+
+func Validate(msg Msg) error {
+	l, err := msg.MsgList()
+	if err != nil {
+		return errors.Wrap(err)
```
Comment (alpe) [inline x/batch/msg.go]: 👍

File: x/batch/msg.go [hunk 26]
```diff
@@ -0,0 +1,30 @@
...
+	PathExecuteBatchMsg = "batch/execute"
+)
+
+type Msg interface {
+	weave.Msg
+	x.Validater
+	MsgList() ([]weave.Msg, error)
+}
+
+func Validate(msg Msg) error {
```
Comment (alpe) [inline x/batch/msg.go]: q: why not have this on the application level where you call this from? That would also help with the `MaxBatchMessages` as this limitation can be application specific.

File: x/batch/msg.go (hunk 24 above)
Comment (ruseinov) [reply x/batch/msg.go]: I checked what it returns, it's descriptive enough

File: x/batch/decorator.go [hunk 27]
```diff
@@ -0,0 +1,156 @@
...
+		payments += r.GasPayment
+	}
+
+	data, _ := (&ByteArrayList{Elements: datas}).Marshal()
+	log, _ := (&ByteArrayList{Elements: logs}).Marshal()
+
+	return weave.CheckResult{
+		Data: data,
+		//TODO: Is this good enough conversion? Should be, in theory
+		Log:          string(log),
```
[the remark this answers is not in the document]
Comment (ruseinov) [reply x/batch/decorator.go]: We already encoded log into a protobuf as discussed with ethan, same with data.

File: cmd/bnsd/app/codec.proto [hunk 28]
```diff
@@ -57,4 +59,37 @@ enum NftType {
...
+            // nft actions
+            nft.AddApprovalMsg add_approval_msg = 11;
+            nft.RemoveApprovalMsg remove_approval_msg = 12;
+            username.IssueTokenMsg issue_username_nft_msg = 13;
+            username.AddChainAddressMsg add_username_address_nft_msg = 14;
+            username.RemoveChainAddressMsg remove_username_address_msg = 15;
+            blockchain.IssueTokenMsg issue_blockchain_nft_msg = 16;
+            ticker.IssueTokenMsg issue_ticker_nft_msg = 17;
+            bootstrap_node.IssueTokenMsg issue_bootstrap_node_nft_msg = 18;
+            BatchMsg batch_msg = 19;
```
[the remark this answers is not in the document]
Comment (ruseinov) [reply cmd/bnsd/app/codec.proto]: This is outdated

File: x/batch/decorator.go (hunk 27 above)
[the remark this answers is not in the document]
Comment (ruseinov) [reply x/batch/decorator.go]: @ethanfrey @webmaster128 can you please chip in here, some history: https://github.com/iov-one/weave/pull/188#discussion_r234531843

[the remark this answers is not in the document]
Comment (ruseinov) [reply x/batch/decorator.go]: @ethanfrey @alpe @webmaster128 one thing here: I think the problem with protobuf approach is that we don't get consistent log strings, as we are using protobuf in batch, but not in other messages. Hence, we don't know what to expect.

Also, log messages are not human-readable when coded in protobuf and printed.

[the remark this answers is not in the document]
Comment (alpe) [reply x/batch/decorator.go]: Just want to add the fact, that we are not even consistent with log type in batch results. In case there is an error, we return this as a string instead.

File: cmd/bcpd/app/msg.go (hunk 18 above)
Comment (ruseinov) [reply cmd/bcpd/app/msg.go]: @alpe I think you are right. 
@ethanfrey would you mind if I convert this and the tx switch cases to reflection instead? it is such a pain to maintain that.

Comment (ethanfrey) [reply cmd/bcpd/app/msg.go]: I don't know how you intend to fix this with reflection. But if you can write and test a generic function for this in less than 2 hours, go for it. Otherwise, I don't see this as priority now, and can be made an issue for future pr.

File: x/batch/decorator.go (hunk 20 above)
Comment (ruseinov) [reply x/batch/decorator.go]: we don't "store" a weave.Tx, we comply to an interface which is crucial for this whole thing to work.

File: cmd/bcpd/app/msg.go (hunk 18 above)
Comment (ruseinov) [reply cmd/bcpd/app/msg.go]: @ethanfrey that should be "easily" fixable via reflection, because these messages comply to the same interface and then they have 1 property each which I can get. 

I'll look into it.

**Comment by ruseinov** [comment]
@alpe finished fixes, I think we are good to go.
I will add a ticket about reflection for later

**Comment by ruseinov** [comment]
Needs unit tests, package-level docs and possibly an acceptance test scenario

**Comment by ruseinov** [comment]
@alpe take a look at this one for a good example of why convey and mocks https://github.com/iov-one/weave/pull/188/commits/f8c611f0ab00be34d482932c2b318d3b51fe5cba
and that's a simple case.
When I'm finished with decorator tests it's going to be way more interesting.

**Comment by ruseinov** [comment]
@alpe all done, no need to update acceptance as batch is disabled for bnsd.

@alpe @husio @ethanfrey please take a close look at https://github.com/iov-one/weave/pull/188/files#diff-9d671778477b5502fe5fc243fd6adbab to see the reasons to use proper testing tools as opposed to using bare minimum.

I bet if we migrated to that we could reduce our test codebase, improve readability and speed up writing tests.

I'm not sure if it's only me, but some of the old school tests in this repo take ages for me to comprehend and build upon.  
Anyhow, something to think about.

File: cmd/bcpd/app/msg.go [hunk 29]
```diff
@@ -0,0 +1,55 @@
...
+
+func (*BatchMsg) Path() string {
+	return batch.PathExecuteBatchMsg
+}
+
+func (msg *BatchMsg) MsgList() ([]weave.Msg, error) {
+	messages := make([]weave.Msg, len(msg.Messages))
+	// make sure to cover all messages defined in protobuf
+	for i, m := range msg.Messages {
+		res, err := func() (weave.Msg, error) {
```
Comment (husio) [inline cmd/bcpd/app/msg.go]: You don't need anonymous function, you can type cast without it.

File: cmd/bcpd/app/msg.go [hunk 30]
```diff
@@ -0,0 +1,55 @@
...
+			case *BatchMsg_Union_UpdateContractMsg:
+				return t.UpdateContractMsg, nil
+			case *BatchMsg_Union_SetValidatorsMsg:
+				return t.SetValidatorsMsg, nil
+			default:
+				return nil, errors.ErrUnknownTxType(t)
+			}
+		}()
+		if err != nil {
+			return messages, err
```
Comment (husio) [inline cmd/bcpd/app/msg.go]: If you want to return messages together with error, it's better to create the result slice as `make([]weave.Msg, 0, len(msg.Messages))` - this way you won't have nil messages in it.

File: cmd/bnsd/app/app.go [hunk 31]
```diff
@@ -50,6 +50,8 @@ func Chain(minFee x.Coin, authFn x.Authenticator) app.Decorators {
 		namecoin.NewFeeDecorator(authFn, minFee),
 		// cannot pay for fee with hashlock...
 		hashlock.NewDecorator(),
+		// make sure we execute all the transactions in batch before the save point
+		//batch.NewDecorator(),
```
Comment (husio) [inline cmd/bnsd/app/app.go]: Is this commented on purpose?

File: cmd/bnsd/app/app_batch_test.go [hunk 32]
```diff
@@ -0,0 +1,146 @@
...
+//	if happy {
+//		So(0, ShouldEqual, dres.Code)
+//	}
+//
+//	app.EndBlock(abci.RequestEndBlock{})
+//	cres := app.Commit()
+//
+//	So(cres.Data, ShouldNotBeEmpty)
+//	return dres
+//}
```
Comment (husio) [inline cmd/bnsd/app/app_batch_test.go]: If they are no longer valid and cannot be fixed, I think it's better to remove them. They are already in git, so you can bring them back at any point.

File: x/batch/decorator.go [hunk 33]
```diff
@@ -0,0 +1,166 @@
...
+func (tx *BatchTx) GetMsg() (weave.Msg, error) {
+	return tx.msg, nil
+}
+
+// Check iterates through messages in a batch transaction and passes them
+// down the stack
+func (d Decorator) Check(ctx weave.Context, store weave.KVStore, tx weave.Tx,
+	next weave.Checker) (weave.CheckResult, error) {
+	var res weave.CheckResult
+	var err error
```
Comment (husio) [inline x/batch/decorator.go]: No need to declare error, it's being created the line below with `:=`

File: x/batch/decorator.go [hunk 34]
```diff
@@ -0,0 +1,166 @@
...
+		GasPayment:   payments,
+	}
+}
+
+// Deliver iterates through messages in a batch transaction and passes them
+// down the stack
+func (d Decorator) Deliver(ctx weave.Context, store weave.KVStore, tx weave.Tx,
+	next weave.Deliverer) (weave.DeliverResult, error) {
+	var res weave.DeliverResult
+	var err error
```
Comment (husio) [inline x/batch/decorator.go]: No need to declare error, it's being created with `:=` line below.

File: x/batch/doc.go [hunk 35]
```diff
@@ -0,0 +1,14 @@
...
+> Batch transaction holds a list of messages
+> that a given application can process. What this means
+> is we can wrap several "transactions" within one message.
+> The transaction fails if any of the messages fail to be processed.
+> Note that fees, sigs and other extensions that don't rely on messages
+> are only applied once per transaction, which means that all the "embedded"
+> transactions don't hit the middleware.
+
+*/
+package batch
```
Comment (husio) [inline x/batch/doc.go]: :heart:

**Comment by ruseinov** [comment]
addressed all the issues that weren't a personal preference, this is ready to go upstream I guess

File: cmd/bcpd/app/msg.go (hunk 29 above)
Comment (ruseinov) [reply cmd/bcpd/app/msg.go]: Also it is done because there is a loop and two return params, which makes things easier if they are wrapped like this.

**Comment by ruseinov** [comment]
@husio if you can take a quick peek at latest changes and approve - that'd be awesome.
I have addressed most of your comments and replied to others, gotta get this one out the door finally
